// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM-b4_nT6aCzGzmm8pzbCE5_3jMwWjfmI',
    appId: '1:1092772613960:web:85a1aa812a131af9772d7d',
    messagingSenderId: '1092772613960',
    projectId: 'project-flower-d74f3',
    authDomain: 'project-flower-d74f3.firebaseapp.com',
    storageBucket: 'project-flower-d74f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkgalcy8km8fTKL67lIpLT-90-pGbr1P4',
    appId: '1:1092772613960:android:7cb01e43e5760e4c772d7d',
    messagingSenderId: '1092772613960',
    projectId: 'project-flower-d74f3',
    storageBucket: 'project-flower-d74f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_y0GbQ-2vLoa8Y3cXns32bzR2XUS1oeI',
    appId: '1:1092772613960:ios:8b1717a88ded3f18772d7d',
    messagingSenderId: '1092772613960',
    projectId: 'project-flower-d74f3',
    storageBucket: 'project-flower-d74f3.firebasestorage.app',
    androidClientId: '1092772613960-r8pe10uhfc3qi57ash700rqov9idkhqb.apps.googleusercontent.com',
    iosClientId: '1092772613960-hvnvd3det9nc19ltndev19hvvo9dejv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_y0GbQ-2vLoa8Y3cXns32bzR2XUS1oeI',
    appId: '1:1092772613960:ios:8b1717a88ded3f18772d7d',
    messagingSenderId: '1092772613960',
    projectId: 'project-flower-d74f3',
    storageBucket: 'project-flower-d74f3.firebasestorage.app',
    androidClientId: '1092772613960-r8pe10uhfc3qi57ash700rqov9idkhqb.apps.googleusercontent.com',
    iosClientId: '1092772613960-hvnvd3det9nc19ltndev19hvvo9dejv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
